<#include "/head.ftl" >
<body>
	<div id='wrap'>
	<#include "/banner.ftl">
		<div id='inner-wrap'>
	<div id='left'>
	<div id='menu'>
		<a href='./protocol'><img src='./images/logo.png' border='0'></a>
		<ul id='navmenu'>
		<li><a class='selectable' title='Access the (Q)MRF Inventory' href='./protocol'>(Q)MRF Inventory</a></li>
		<li><a class='selectable' title='User manual' href='http://qmrf.sf.net/manual'>User manual</a></li>
		<li><a class='selectable' title='Reviewers template' href='http://qmrf.sf.net/template'>Reviewers template</a></li>
		<li><a class='selectable' title='QMRF Editor' href='http://qmrf.sf.net/editor'>QMRF Editor</a></li>
		<li><a class='selectable' title='OECD Principles' href='http://ihcp.jrc.ec.europa.eu/our_labs/computational_toxicology/background/oecd-principles'>OECD Principles</a></li>
		<li><a class='selectable' title='F.A.Q' href='http://qmrf.sf.net/faq'>F.A.Q</a></li>
		</ul>
	</div>
	</div>
	
	<div id='content'>
	<h1>What is the (Q)SAR Inventory</h1>
	
	<div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 12pt;">
	In the regulatory assessment of chemicals (e.g. under REACH), <b>(Q)SAR models</b> are playing an increasingly important 
	role in predicting properties for hazard and risk assessment. This implies both a need to be able to identify
	relevant (Q)SARs and to use them to derive estimates and/or have access to their precalculated estimates.
	To help meet these needs, we are developing a database of (Q)SAR models (i.e. an inventory of information on the models).
	The JRC QSAR Model Database is freely accessible from <a href='./protocol'>this web site</a>.
	</div>
	<div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 12pt;">
	The <b>QSAR Model Reporting Format (QMRF)</b> is a harmonised template for summarising and reporting key information on
	(Q)SAR models, including the results of any validation studies. The information is structured according to the OECD (Q)SAR validation
	principles. 
	</div>
	<div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 12pt;">
	The <b>QSAR Prediction Reporting Format (QPRF)</b> is a harmonised template for summarising and reporting substance-specific predictions generated by 
	(Q)SAR models.
	</div>
	<div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 12pt;">
	All <b>substances</b>, available in the QMRF Database can be searched by exact, substructure or similar structure.
	</div>
	<div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 14pt; text-align:center;">
	<a href='./protocol'>Access the Inventory</a>
    </div>

    
    <div class=".ui-widget-content" style="margin-top: 20px; padding: 0 .5em; font-size: 12pt;">
    <h3>Please send your models to us and have them included in the database</h3>
    Contact: <a href='mailto:JRC-IHCP-COMPUTOX@ec.europa.eu'>JRC-IHCP-COMPUTOX@ec.europa.eu</a>	
    </div>
		</div> 	
		<div class='pusher'></div>
	</div>
    </div>

<#include "/footer.ftl">
</body></html>