<#include "/html.ftl" >
<head>
<#include "/head.ftl" >
</head>
<body>
	<div class='w_wrap'>
	<#include "/banner.ftl">
	<#include "/w_menu.ftl">
	<div class='w_content'>
		<p class='w_p_header'>Welcome to the QMRF Inventory</p>
		<p class='w_p'>
			In the regulatory assessment of chemicals (e.g. under REACH), <b>(Q)SAR models</b> are playing an increasingly important role in predicting properties for hazard and risk assessment. This implies both a need to be able to identify relevant (Q)SARs and to use them to derive estimates and/or have access to their precalculated estimates. To help meet these needs, we are developing a database of (Q)SAR models (i.e. an inventory of information on the models). The JRC QSAR Model Database is freely accessible through this web site.
		</p>
		<p class='w_p'>
			The <b>(Q)SAR Model Reporting Format (QMRF)</b> is a harmonised template for summarising and reporting key information on (Q)SAR models, including the results of any validation studies. The information is structured according to the OECD (Q)SAR validation principles. 
		</p>
		<p class='w_p'>
			The <b>(Q)SAR Prediction Reporting Format (QPRF)</b> is a harmonised template for summarising and reporting substance-specific predictions generated by (Q)SAR models.
		</p>
		<p class='w_p'>
			All substances, available in the QMRF Database, can be searched by exact or similar structure, or by a substructure.
		</p>
    	<p class='w_p_send'>Please send us your models to have them included in the database:
    		<a class='email' href='mailto:${qmrf_email}'>${qmrf_email}</a>	
    	</p>
	</div> <#-- w_content -->
	
	<#-- Prevents the footer from hiding the last line on smaller screens. -->
	<div class='pusher'></div>
	
	</div> <#-- w_wrap -->
	
<#include "/footer.ftl">
<#include "/scripts-welcome.ftl">
</body>
</html>